{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubilitics.secretName" . }}
  labels:
    {{- include "kubilitics.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secret.authJWTSecret }}
  auth-jwt-secret: {{ .Values.secret.authJWTSecret | b64enc }}
  {{- end }}
  {{- if .Values.secret.authAdminPass }}
  auth-admin-pass: {{ .Values.secret.authAdminPass | b64enc }}
  {{- end }}
  {{- if .Values.secret.oidcClientSecret }}
  oidc-client-secret: {{ .Values.secret.oidcClientSecret | b64enc }}
  {{- end }}
  {{- if .Values.secret.samlCertificate }}
  saml-certificate: {{ .Values.secret.samlCertificate | b64enc }}
  {{- end }}
  {{- if .Values.secret.samlPrivateKey }}
  saml-private-key: {{ .Values.secret.samlPrivateKey | b64enc }}
  {{- end }}
  {{- if .Values.secret.mfaEncryptionKey }}
  mfa-encryption-key: {{ .Values.secret.mfaEncryptionKey | b64enc }}
  {{- end }}
  {{- if .Values.secret.data }}
  {{- range $key, $value := .Values.secret.data }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
  {{- end }}
{{- end }}
