{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubilitics.serviceAccountName" . }}
  labels:
    {{- include "kubilitics.labels" . | nindent 4 }}
  {{- if .Values.rbac.serviceAccount.annotations }}
  annotations:
    {{- toYaml .Values.rbac.serviceAccount.annotations | nindent 4 }}
  {{- end }}
{{- end }}
